version: "3.9"
volumes:
  php-fpm-socket:
  db-store:
  psysh-store:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./app
        target: /work
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    container_name: my-php-framework.app
    # environment:
    #   - DB_CONNECTION=pgsql
    #   - DB_HOST=db
    #   - DB_PORT=5432
    #   - DB_DATABASE=${DB_NAME:-laravel_local}
    #   - DB_USERNAME=${DB_USER:-phper}
    #   - DB_PASSWORD=${DB_PASS:-secret}

  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/nginx/Dockerfile
  #   ports:
  #     - target: 80
  #       published: ${WEB_PORT:-80}
  #       protocol: tcp
  #       mode: host
  #   volumes:
  #     - type: volume
  #       source: php-fpm-socket
  #       target: /var/run/php-fpm
  #       volume:
  #         nocopy: true
  #     - type: bind
  #       source: ./app
  #       target: /work
  #   container_name: my-php-framework.web

  # db:
  #   build:
  #     context: .
  #     dockerfile: ./docker/psql/Dockerfile
  #   ports:
  #     - target: 5432
  #       published: ${DB_PORT:-5432}
  #       protocol: tcp
  #       mode: host
  #   volumes:
  #     - type: volume
  #       source: db-store
  #       target: /var/lib/psql
  #       volume:
  #         nocopy: true
  #   container_name: my-php-framework.db
  #   environment:
  #     - POSTGRES_DB=${DB_NAME:-laravel_local}
  #     - POSTGRES_USER=${DB_USER:-phper}
  #     - POSTGRES_PASSWORD=${DB_PASS:-secret}
  #     - TZ=Asia/Tokyo
  #     - PGTZ=Asia/Tokyo
